---
title: "Linear models"
description: |
  An introduction to the bayesian linear regression model.
author:
  - name: Diogo Melo 
    url: 
    affiliation:
    affiliation_url:
date: "2025-01-27"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Slides

```{r slides}
xaringanExtra::embed_xaringan("02_linear_models/slides.html")
```
[Open slides in new window](02_linear_models/slides.html)

[Slides PDF](02_linear_models/SimpleLinearModels.pdf)

```{r slides 2}
xaringanExtra::embed_xaringan("03_extending_linear_models/slides.html")
```

[Open slides in new window](03_extending_linear_models/slides.html)

[Slides PDF](03_extending_linear_models/ExtendingLinearModels.pdf)

# Lab

[Linear regression Lab](labs/LinearModels/lab.html)

## References

+ Gelman, A., Hill, J. & Vehtari, A. Regression and Other Stories. (Cambridge University Press, 2020).

+ McElreath, R., 2018. Statistical Rethinking: A Bayesian Course with Examples in R and Stan, 2nd ed. CRC Press.

+ Bayesian Data Analysis, Third Edition, Andrew Gelman, John B. Carlin, Hal S. Stern, David B. Dunson, Aki Vehtari, Donald B. Rubin, Chapman and Hall/CRC, 2013.





